name: recipeapp

services:
  database:
    image:  postgres@sha256:473783dca8870bbde3a32370c72a9de9406f37d048c05d7b5c40f93e7c23d827
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
